name: Pipeline

on: [push, workflow_dispatch]

env:
  PYTHONPATH: C://

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup env
        uses: actions/setup-python@v4
        with:
          version: 4
          
      - name: install packages
        run: pip install development-requirements
        
      - name: lint code
        run: |
          flake8 *.py
          pylint *.py
          simpl *.py

      - name: run unit testing
        run: python unittest --verbose --failtest

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest

    permissions: 
      packages: write

    steps:  
      - uses: actions/checkout@v4
      - name: setup env
        uses: actions/setup-python@v4
        with:
          version: 4
      - name: setup docker
        uses: docker/build-package@v4
        with:
          version: 4
          
      - name: build docker image
        uses: docker/build-image@v4
        with:
          context:
          arch: linux/amd64
          tags: ${{ vars.tags }}
          labels: ${{ vars.labels }}


      
  test-image:
  
  deploy: 

